"""Audit local metrics for planned cross-sector DeepSeek panels.

Use this before calling DeepSeek on paired ranker-anchor panels. It reads the
evidence packs generated by dry-runs, maps their group ids back to local
walk-forward detail metrics, and decides whether the panel is worth token spend.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

REPORT_DIR = ROOT / "reports" / "date_generalization"
FORBIDDEN_KEYS = {
    "return_5d",
    "return_10d",
    "return_20d",
    "future_return_5d",
    "future_return_10d",
    "future_return_20d",
    "fwd_ret_20d",
    "pool_excess_20d",
    "rank_pct_in_date",
    "rank_pct_in_industry_date",
    "gt_status",
    "gt_pass",
    "rule_outcome_label",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit planned cross-sector panel before DS spend.")
    parser.add_argument("--detail", type=Path, default=REPORT_DIR / "cross_sector_ranker_search_v2_detail.csv")
    parser.add_argument(
        "--plans",
        nargs="+",
        required=True,
        help="Plan specs in label:prefix:score_name format. First plan is the paired baseline.",
    )
    parser.add_argument("--output-prefix", default="cross_sector_planned_panel_audit_v1")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    plans = [parse_plan(spec) for spec in args.plans]
    detail = pd.read_csv(args.detail, low_memory=False)
    rows = []
    hygiene_rows = []
    for plan in plans:
        groups, hygiene = load_plan_groups(plan)
        hygiene_rows.append({"label": plan["label"], **hygiene})
        subset = detail[
            detail["comparison_group_id"].astype(str).isin(groups)
            & detail["decision_frequency"].astype(str).eq("every_2_weeks")
            & detail["score_name"].astype(str).eq(plan["score_name"])
        ].copy()
        subset["plan_label"] = plan["label"]
        subset["source_prefix"] = plan["prefix"]
        rows.append(subset)
    planned_detail = pd.concat(rows, ignore_index=True) if rows else pd.DataFrame()
    aggregate = aggregate_metrics(planned_detail)
    by_block = aggregate_metrics(planned_detail, keys=["plan_label", "time_block"])
    paired = paired_vs_baseline(planned_detail, baseline_label=plans[0]["label"])
    gate = build_gate(aggregate, by_block, paired, baseline_label=plans[0]["label"])
    hygiene = pd.DataFrame(hygiene_rows)

    prefix = safe_prefix(args.output_prefix)
    paths = {
        "detail": REPORT_DIR / f"{prefix}_detail.csv",
        "aggregate": REPORT_DIR / f"{prefix}_aggregate.csv",
        "by_block": REPORT_DIR / f"{prefix}_by_block.csv",
        "paired": REPORT_DIR / f"{prefix}_paired_vs_baseline.csv",
        "hygiene": REPORT_DIR / f"{prefix}_hygiene.csv",
        "gate": REPORT_DIR / f"{prefix}_gate.csv",
        "report": REPORT_DIR / f"{prefix}.md",
    }
    planned_detail.to_csv(paths["detail"], index=False, encoding="utf-8-sig")
    aggregate.to_csv(paths["aggregate"], index=False, encoding="utf-8-sig")
    by_block.to_csv(paths["by_block"], index=False, encoding="utf-8-sig")
    paired.to_csv(paths["paired"], index=False, encoding="utf-8-sig")
    hygiene.to_csv(paths["hygiene"], index=False, encoding="utf-8-sig")
    gate.to_csv(paths["gate"], index=False, encoding="utf-8-sig")
    paths["report"].write_text(render_report(plans, aggregate, by_block, paired, hygiene, gate, paths), encoding="utf-8")
    print(f"plans={len(plans)} groups={planned_detail['comparison_group_id'].nunique() if not planned_detail.empty else 0}")
    print(f"wrote: {paths['report']}")


def parse_plan(spec: str) -> dict[str, str]:
    parts = spec.split(":", 2)
    if len(parts) != 3:
        raise ValueError(f"bad plan spec, expected label:prefix:score_name: {spec}")
    return {"label": parts[0], "prefix": parts[1], "score_name": parts[2]}


def load_plan_groups(plan: dict[str, str]) -> tuple[set[str], dict[str, Any]]:
    path = REPORT_DIR / f"{safe_prefix(plan['prefix'])}_evidence_pack.jsonl"
    if not path.exists():
        raise FileNotFoundError(path)
    groups: set[str] = set()
    future_hits: list[str] = []
    duplicate_groups: list[str] = []
    pack_count = 0
    text = path.read_text(encoding="utf-8")
    for line in text.splitlines():
        if not line.strip():
            continue
        pack_count += 1
        obj = json.loads(line)
        group_id = str(obj.get("comparison_group_id", ""))
        groups.add(group_id.replace("every_2_weeks__", ""))
        codes = [str(item.get("code", "")).zfill(6) for item in obj.get("candidates", [])]
        if len(codes) != len(set(codes)):
            duplicate_groups.append(group_id)
        walk_forbidden(obj, future_hits)
    return groups, {
        "pack_count": pack_count,
        "unique_groups": len(groups),
        "future_key_hits": len(future_hits),
        "future_key_hit_names": ";".join(sorted(set(future_hits))),
        "secret_like_hits": text.count("sk-"),
        "duplicate_code_groups": ";".join(duplicate_groups),
    }


def walk_forbidden(value: Any, hits: list[str]) -> None:
    if isinstance(value, dict):
        for key, item in value.items():
            if key in FORBIDDEN_KEYS:
                hits.append(str(key))
            walk_forbidden(item, hits)
    elif isinstance(value, list):
        for item in value:
            walk_forbidden(item, hits)


def aggregate_metrics(frame: pd.DataFrame, keys: list[str] | None = None) -> pd.DataFrame:
    if frame.empty:
        return pd.DataFrame()
    group_keys = keys or ["plan_label"]
    rows = []
    for key_values, group in frame.groupby(group_keys, sort=True):
        if not isinstance(key_values, tuple):
            key_values = (key_values,)
        row = {key: value for key, value in zip(group_keys, key_values)}
        row.update(
            {
                "n_groups": int(group["comparison_group_id"].nunique()),
                "top1_excess_mean": round(float(pd.to_numeric(group["top1_excess_20d"], errors="coerce").mean()), 6),
                "top2_excess_mean": round(float(pd.to_numeric(group["top2_excess_20d"], errors="coerce").mean()), 6),
                "top1_positive_rate": round(float(group["top1_positive"].astype(bool).mean()), 6),
                "top2_positive_rate": round(float(pd.to_numeric(group["top2_positive_rate"], errors="coerce").mean()), 6),
                "top1_worst_rate": round(float(group["top1_is_worst"].astype(bool).mean()), 6),
                "regret_mean": round(float(pd.to_numeric(group["top1_regret_vs_best"], errors="coerce").mean()), 6),
            }
        )
        rows.append(row)
    return pd.DataFrame(rows)


def paired_vs_baseline(frame: pd.DataFrame, *, baseline_label: str) -> pd.DataFrame:
    if frame.empty:
        return pd.DataFrame()
    base = frame[frame["plan_label"].eq(baseline_label)][
        ["comparison_group_id", "time_block", "top1_excess_20d", "top2_excess_20d", "top1_positive", "top1_is_worst"]
    ].rename(
        columns={
            "top1_excess_20d": "base_top1_excess",
            "top2_excess_20d": "base_top2_excess",
            "top1_positive": "base_top1_positive",
            "top1_is_worst": "base_top1_worst",
        }
    )
    rows = []
    for label, subset in frame[~frame["plan_label"].eq(baseline_label)].groupby("plan_label", sort=True):
        merged = subset.merge(base, on=["comparison_group_id", "time_block"], how="inner")
        if merged.empty:
            continue
        rows.append(paired_row(label, "ALL", merged))
        for block, group in merged.groupby("time_block", sort=True):
            rows.append(paired_row(label, block, group))
    return pd.DataFrame(rows)


def paired_row(label: str, block: str, group: pd.DataFrame) -> dict[str, Any]:
    return {
        "plan_label": label,
        "time_block": block,
        "n_groups": int(group["comparison_group_id"].nunique()),
        "delta_top1_excess_mean": round(float((group["top1_excess_20d"] - group["base_top1_excess"]).mean()), 6),
        "delta_top2_excess_mean": round(float((group["top2_excess_20d"] - group["base_top2_excess"]).mean()), 6),
        "delta_top1_positive_rate": round(float(group["top1_positive"].astype(float).mean() - group["base_top1_positive"].astype(float).mean()), 6),
        "delta_top1_worst_rate": round(float(group["top1_is_worst"].astype(float).mean() - group["base_top1_worst"].astype(float).mean()), 6),
    }


def build_gate(aggregate: pd.DataFrame, by_block: pd.DataFrame, paired: pd.DataFrame, *, baseline_label: str) -> pd.DataFrame:
    if aggregate.empty:
        return pd.DataFrame()
    out = aggregate.copy()
    block_min = by_block.groupby("plan_label", sort=True).agg(
        block_top2_min=("top2_excess_mean", "min"),
        block_top1_min=("top1_excess_mean", "min"),
        block_worst_max=("top1_worst_rate", "max"),
    )
    out = out.merge(block_min, on="plan_label", how="left")
    paired_all = paired[paired["time_block"].eq("ALL")].drop(columns=["time_block"], errors="ignore")
    out = out.merge(paired_all, on="plan_label", how="left")
    out["worth_flash_call"] = (
        out["plan_label"].eq(baseline_label)
        | (
            (pd.to_numeric(out["delta_top2_excess_mean"], errors="coerce") > 0.25)
            & (pd.to_numeric(out["block_top2_min"], errors="coerce") >= -2.5)
            & (pd.to_numeric(out["block_worst_max"], errors="coerce") <= 0.08)
        )
    )
    out["gate_note"] = out.apply(lambda row: gate_note(row, baseline_label=baseline_label), axis=1)
    return out


def gate_note(row: pd.Series, *, baseline_label: str) -> str:
    if row.get("plan_label") == baseline_label:
        return "baseline"
    notes = []
    if pd.to_numeric(pd.Series([row.get("delta_top2_excess_mean")]), errors="coerce").iloc[0] <= 0.25:
        notes.append("paired_top2_delta_weak")
    if pd.to_numeric(pd.Series([row.get("block_top2_min")]), errors="coerce").iloc[0] < -2.5:
        notes.append("block_top2_min_too_negative")
    if pd.to_numeric(pd.Series([row.get("block_worst_max")]), errors="coerce").iloc[0] > 0.08:
        notes.append("top1_worst_block_risk")
    return "pass_flash_candidate" if not notes else ";".join(notes)


def render_report(
    plans: list[dict[str, str]],
    aggregate: pd.DataFrame,
    by_block: pd.DataFrame,
    paired: pd.DataFrame,
    hygiene: pd.DataFrame,
    gate: pd.DataFrame,
    paths: dict[str, Path],
) -> str:
    lines = [
        "# Cross-Sector Planned Panel Audit v1",
        "",
        "本报告在调用 DeepSeek 前评估 planned evidence packs 的本地结果，避免在本地 gate 已失败时继续烧 token。",
        "",
        "## Plans",
        "",
        pd.DataFrame(plans).to_markdown(index=False),
        "",
        "## Hygiene",
        "",
        markdown_table(hygiene),
        "",
        "## Aggregate",
        "",
        markdown_table(aggregate),
        "",
        "## Paired Delta vs Baseline",
        "",
        markdown_table(paired),
        "",
        "## By Block",
        "",
        markdown_table(by_block),
        "",
        "## Gate",
        "",
        markdown_table(gate),
        "",
        "## Interpretation",
        "",
        "- `worth_flash_call=True` 是进入 Flash paired 的前置条件，不是升默认条件。",
        "- 若候选在 H2026_1 或任一 block 明显输给 baseline，应先重新抽样或改 ranker，而不是直接调用 Pro。",
        "- baseline 也会保留在 Flash paired 中，用于衡量 Agent 是否维持或破坏确定性排序。",
        "",
        "## Artifacts",
        "",
        *(f"- `{path}`" for path in paths.values()),
        "",
    ]
    return "\n".join(lines)


def markdown_table(frame: pd.DataFrame) -> str:
    if frame.empty:
        return "_empty_"
    try:
        return frame.to_markdown(index=False)
    except Exception:
        return frame.to_csv(index=False)


def safe_prefix(value: str) -> str:
    return "".join(char if char.isalnum() or char in {"_", "-"} else "_" for char in str(value)).strip("_")


if __name__ == "__main__":
    main()
